package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller //This means that this class is a Controller
@RequestMapping(path="/demo")// This means URL's start with /demo
public class MainController {
    @Autowired //This means to get the bean called userRepository
                //That userRepository is auto-generated by Spring
                //And we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") //Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email) {
        //@ResponseBody means the returned String is the response, not a view name
        //@RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
    }
}
